# Generated by Django 4.2.23 on 2026-01-30 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pph21_plugin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeetaxprofile',
            options={'verbose_name': 'Employee Tax Profile (PPh21)', 'verbose_name_plural': 'Employee Tax Profiles (PPh21)'},
        ),
    ]
